spring:
  application:
    name: medicore

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true

  config:
    import: optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  servlet:
    context-path: /api

app:
  doctor:
    working-hours:
      start: "08:00"
      end: "17:00"
  scheduling:
    slot-duration-minutes: 60

  aws:
    s3:
      folder-name: test
      file-name: report
      url-duration-min: 30

  jwt:
    accessTokenExpirationTimeMs: 900_000      # 15 min
    refreshTokenExpirationTimeMs: 2_592_000_000 # 30 days