spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}

openapi:
  resource-server-url: ${RESOURCE_SERVER_URL}
  server-description: Development server