spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
  frontend:
    base-url: ${BASE_URL}
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}

openapi:
  resource-server-url: ${RESOURCE_SERVER_URL}
  server-description: Development server

cors:
  allowed-origins:
    - http://localhost:5173